name: deploy-book

on:
  push:
    branches:
    - '*'
    - '*/*'

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: conda env create
      run: | 
        source '/usr/share/miniconda/etc/profile.d/conda.sh'
        conda create -n jbook -c conda-forge jupyter-book python=3.11

    - name: Build the book
      run: |
        source '/usr/share/miniconda/etc/profile.d/conda.sh'
        conda activate jbook
        jupyter-book build .